# Generated by Django 4.2.2 on 2023-06-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0004_help"),
    ]

    operations = [
        migrations.CreateModel(
            name="contactme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=13)),
                ("message", models.TextField()),
            ],
        ),
    ]
