# Generated by Django 4.2.2 on 2023-06-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0005_contactme"),
    ]

    operations = [
        migrations.CreateModel(
            name="register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=20)),
                ("cpassword", models.CharField(max_length=20)),
            ],
        ),
    ]
