# Generated by Django 4.2.2 on 2023-06-27 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0006_register"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="register",
            name="cpassword",
        ),
    ]
