# Generated by Django 4.2.2 on 2023-06-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0007_remove_register_cpassword"),
    ]

    operations = [
        migrations.CreateModel(
            name="article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("Image", models.ImageField(upload_to="")),
                ("Writter", models.CharField(max_length=1000)),
            ],
        ),
    ]
