# Generated by Django 4.2.2 on 2023-06-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0008_article"),
    ]

    operations = [
        migrations.CreateModel(
            name="editor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Image", models.ImageField(upload_to="")),
                ("name", models.CharField(max_length=1000)),
                ("Website", models.CharField(max_length=1000)),
            ],
        ),
    ]
