# Generated by Django 4.2.2 on 2023-06-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0010_article_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="Image",
            field=models.ImageField(default=None, upload_to="data"),
        ),
    ]
