# Generated by Django 4.2.2 on 2023-06-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0011_alter_article_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="register",
            name="Address",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="register",
            name="Country",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="register",
            name="Pincode",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="register",
            name="State",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="register",
            name="bio",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="register",
            name="phoneno",
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
    ]
