# Generated by Django 4.2.2 on 2023-06-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0013_alter_register_address_alter_register_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="bio",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
