# Generated by Django 4.2.2 on 2023-06-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0014_alter_register_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
