# Generated by Django 4.2.2 on 2023-06-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0016_rename_bio_register_mybio"),
    ]

    operations = [
        migrations.AddField(
            model_name="register",
            name="detail",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
