# Generated by Django 4.2.2 on 2023-06-30 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0017_register_detail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="register",
            name="mybio",
        ),
    ]
