# Generated by Django 4.2.2 on 2023-07-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0018_remove_register_mybio"),
    ]

    operations = [
        migrations.AddField(
            model_name="register",
            name="Image",
            field=models.ImageField(default=None, upload_to="media"),
        ),
    ]
