# Generated by Django 4.2.2 on 2023-07-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0019_register_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="Image",
            field=models.ImageField(blank=True, null=True, upload_to="media"),
        ),
    ]
