# Generated by Django 4.2.2 on 2023-07-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0022_remove_register_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="register",
            name="pic",
            field=models.ImageField(blank=True, upload_to="data"),
        ),
    ]
