# Generated by Django 4.2.2 on 2023-07-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0024_remove_register_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="register",
            name="profile",
            field=models.ImageField(blank=True, null=True, upload_to="data"),
        ),
    ]
